name: Continuous Integration
on: [push]
jobs:
  tox:
    name: Tox Tests
    strategy:
      matrix:
        os:
          - ubuntu-16.04
        tox:
          - env: py36
            python-version: 3.6
          - env: py37
            python-version: 3.7
          - env: py38
            python-version: 3.8
          - env: coverage
            python-version: 3.6
          - env: style
            python-version: 3.6
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
            python-version: ${{ matrix.tox.python-version }}
      - name: Install Tox
        run: python -m pip install tox
      - name: Test ${{ matrix.tox.env }}
        run: tox -v -e ${{ matrix.tox.env }}
